name: "Rename Google Drive File"
description: "This actions renames file in Google Drive"
author: "Slate IQ"

inputs:
  fileId:
    description: "Google Drive file ID"
    required: true
  fileName:
    description: "The new name of the file"
    required: true
  credentials:
    description: "credentials.json file"
    required: true

runs:
  using: node20
  main: dist/index.js
